Fixing formatting & run instructions.
TheMGRF/NerdBot pull request #112
Opened 2023-07-27 18:56 UTC by wiviw5

This includes changes to README.md and a new page for RUNNING.md that will be updated more in the future as changes are made.

2023-07-27 19:01 UTC, wiviw5 commented
If you would like to preview the changes for yourself, you can at:

https://github.com/wiviw5/NerdBot/blob/fix_readmes/README.md
https://github.com/wiviw5/NerdBot/blob/fix_readmes/RUNNING.md

2023-07-28 01:58 UTC, Aerhhh requested changes

2023-07-28 01:58 UTC, Aerhhh commented on CONTRIBUTING.md
> +
```suggestion

 - This file is automatically updated when values are added, removed, or changed.

```

2023-07-28 01:58 UTC, Aerhhh commented on CONTRIBUTING.md
> +- Emoji's all set (Agree, disagree, neutral, and greenlit)
Make this into another bulleted list and change "Emoji's" to "Emojis"

2023-07-28 01:58 UTC, Aerhhh commented on CONTRIBUTING.md
> +- Suggestion forum id for suggestion parsing.
```suggestion
- Channel ID of a suggestions channel in order to curate suggestions
```

2023-07-28 01:58 UTC, Aerhhh commented on CONTRIBUTING.md
> +- Item gen channel(s) for allowing itemgen to work in them.
```suggestion
- Channel ID('s) of item generator channel(s) to allow the item generation commands to be used
```

2023-07-28 01:58 UTC, Aerhhh commented on CONTRIBUTING.md
> +- Tag ID set for greenlit to work.
Not needed anymore since it checks by name instead of ID

2023-07-28 01:58 UTC, Aerhhh commented on CONTRIBUTING.md
> +or `dev.config.json`
Remove the newline

2023-07-28 01:58 UTC, Aerhhh commented on CONTRIBUTING.md
> +Changes to the configuration file require the bot to be restarted.
There's a `/config reload` command to hot-reload the config while the bot is active

2023-07-28 02:19 UTC, merged