Automated Skyblock update thread detection & posting
TheMGRF/NerdBot pull request #161
Opened 2023-11-12 02:18 UTC by wiviw5

Long wanted automation for sending skyblock update threads in the discord with pings!

2023-11-12 03:10 UTC, Aerhhh requested changes

2023-11-12 03:10 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadParser.java
> +    }
Should separate this into its own class

2023-11-12 03:10 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadParser.java
> +
Remove extra empty line

2023-11-12 03:10 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/SkyblockUpdateDataHandler.java
> +
Remove empty line

2023-11-12 03:10 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/SkyblockUpdateDataHandler.java
> +
Remove the empty lines here

2023-11-12 03:16 UTC, Aerhhh requested changes

2023-11-12 03:16 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadParser.java
> +
Remove extra empty line

2023-11-12 03:16 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadParser.java
> +
Remove extra empty line

2023-11-12 03:47 UTC, Aerhhh requested changes

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadParser.java
> +
Remove blank line

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadParser.java
> +            return parseSkyblockThreads(XML).get(0);
Also make sure this is changed wherever it's used
```suggestion
    public static HypixelThread getLastPostedSkyBlockThread(String xml) {
        try {
            return parseSkyBlockThreads(xml).get(0);
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadParser.java
> +public class SkyblockThreadParser {
```suggestion
public class SkyBlockThreadParser {
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadParser.java
> +    }
```suggestion
    public static List<HypixelThread> parseSkyBlockThreads(String xml) throws ParserConfigurationException, SAXException, IOException {
        SAXParserFactory factory = SAXParserFactory.newInstance();
        SAXParser saxParser = factory.newSAXParser();

        SkyBlockThreadHandler skyBlockThreadHandler = new SkyBlockThreadHandler();
        InputStream targetStream = new ByteArrayInputStream(xml.getBytes());
        saxParser.parse(targetStream, skyBlockThreadHandler);
        return skyBlockThreadHandler.getSkyBlockForum().getThreadList();
    }
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadParser.java
> +    }
```suggestion
    public static class SkyBlockForum {
        private List<HypixelThread> threadList;
    }
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadHandler.java
> +        skyblockForum = new SkyblockThreadParser.SkyblockForum();
```suggestion
        skyBlockForum = new SkyBlockThreadParser.SkyBlockForum();
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadHandler.java
> +        List<SkyblockThreadParser.HypixelThread> articleList = skyblockForum.getThreadlist();
```suggestion
    private SkyBlockThreadParser.HypixelThread latestThread() {
        List<SkyBlockThreadParser.HypixelThread> articleList = skyBlockForum.getThreadList();
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadHandler.java
> +                skyblockForum.getThreadlist().add(new SkyblockThreadParser.HypixelThread());
```suggestion
                skyBlockForum.getThreadList().add(new SkyBlockThreadParser.HypixelThread());
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadHandler.java
> +                    skyblockForum.setThreadlist(new ArrayList<>());
```suggestion
                    skyBlockForum.setThreadList(new ArrayList<>());
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadHandler.java
> +    private SkyblockThreadParser.SkyblockForum skyblockForum;
```suggestion
    private SkyBlockThreadParser.SkyBlockForum skyBlockForum;
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadHandler.java
> +public class SkyblockThreadHandler extends DefaultHandler {
```suggestion
public class SkyBlockThreadHandler extends DefaultHandler {
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/SkyblockUpdateDataHandler.java
> +public class SkyblockUpdateDataHandler {
```suggestion
public class SkyBlockUpdateDataHandler {
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/HypixelThreadURLWatcher.java
> +            handleThread(getLastPostedSkyblockThread(newContent));
```suggestion
            handleThread(getLastPostedSkyBlockThread(newContent));
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/HypixelThreadURLWatcher.java
> +                    handleThread(getLastPostedSkyblockThread(newContent));
```suggestion
                    handleThread(getLastPostedSkyBlockThread(newContent));
```

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyblockThreadHandler.java
> +                    break;
I would probably change these to debug instead

2023-11-12 03:47 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/SkyblockUpdateDataHandler.java
> +
```suggestion
```

2023-11-12 07:59 UTC, wiviw5 commented
Known Issues:

1: articleList being set to null for some reason, possibly due to the code running at the same time

2: For some reason the new content changes when there are no changes.

These two will need to be solved + possibly more.

For 1 thinking we can maybe change up how the list of threads for output is stored?
(Potentially including a list all the way back at the start of the runtime methods to store their results in instead of in class?)

For 2, I am thinking downloading the XML everytime leads to something changing between downloads, I think the proper solution is possibly to rely on something else? Perhaps parsing each minute the new threads and seeing whats new?

2023-11-14 00:51 UTC, Aerhhh requested changes

2023-11-14 00:51 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/HypixelThreadURLWatcher.java
> +    }
```suggestion
    public int getHighestGuid() {
        List<HypixelThread> hypixelThreads = fetchAndParseContent();
        int[] guidList = new int[hypixelThreads.size()];
        
        for (int x = 0; x < hypixelThreads.size(); x++) {
            guidList[x] = hypixelThreads.get(x).getGuid();
        }
        
        return Arrays.stream(guidList).max().getAsInt();
    }
```

2023-11-14 00:51 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/HypixelThreadURLWatcher.java
> +        }
```suggestion
        if (hypixelThreads == null) {
            return;
        }
        
        for (HypixelThread thread : hypixelThreads) {
            if (thread.getGuid() > lastGuid) {
                log.debug("Watched " + url + " and found newest Guid!\nOld Guid: " + lastGuid + "\nNew Guid: " + thread.getGuid());
                lastGuid = thread.getGuid();
                handleThread(thread);
            }
        }
```

2023-11-14 00:51 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/HypixelThreadURLWatcher.java
> +            }
```suggestion
            public void run() {
                List<HypixelThread> hypixelThreads = fetchAndParseContent();
                if (hypixelThreads == null) {
                    return;
                }
                
                for (HypixelThread thread : hypixelThreads) {
                    if (thread.getGuid() > lastGuid) {
                        log.debug("Watched " + url + " and found newest Guid!\nOld GUID: " + lastGuid + "\nNew GUID: " + thread.getGuid());
                        lastGuid = thread.getGuid();
                        handleThread(thread);
                    }
                }
            }
```

2023-11-14 00:51 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/HypixelThreadURLWatcher.java
> +import static net.hypixel.nerdbot.util.watcher.rss.xmlparsers.SkyBlockThreadParser.parseSkyBlockThreads;
Remove these

2023-11-14 00:51 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/SkyBlockUpdateDataHandler.java
> +    }
```suggestion
    public static void handleThread(HypixelThread hypixelThread) {
        ChannelConfig config = NerdBotApp.getBot().getConfig().getChannelConfig();
        TextChannel announcementChannel = ChannelManager.getChannel(config.getAnnouncementChannelId());
        if (announcementChannel == null) {
            log.error("Couldn't find announcement channel!");
            return;
        }
        
        // Simple Check to make sure only SkyBlock threads are sent.
        if (!hypixelThread.getForum().equals("SkyBlock Patch Notes")){
            if (!hypixelThread.getTitle().contains("SkyBlock")){
                return;
            }
        }

        MessageCreateBuilder messageCreateBuilder = new MessageCreateBuilder();
        PingableRole role = RoleManager.getPingableRoleByName("SkyBlock Update Alerts");
        if (role != null) {
            messageCreateBuilder.addContent(RoleManager.formatPingableRoleAsMention(role) + "\n\n");
        }

        messageCreateBuilder.addContent(hypixelThread.getLink());
        announcementChannel.sendMessage(messageCreateBuilder.build()).queue();
    }
```

2023-11-14 00:51 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyBlockThreadHandler.java
> +    private static final String CREATOR = "dc:creator";
```suggestion
public class SkyBlockThreadHandler extends DefaultHandler {

    private static final String DESCRIPTION = "description";
    private static final String ATOMLINK = "atom:link";
    private static final String CHANNEL = "channel";
    private static final String ITEM = "item";
    private static final String TITLE = "title";
    private static final String PUBDATE = "pubDate";
    private static final String LINK = "link";
    private static final String GUID = "guid";
    private static final String CREATOR = "dc:creator";

    @Getter
    private SkyBlockThreadParser.SkyBlockForum skyBlockForum;
    private StringBuilder elementValue;
    private static String forum = null;
```

2023-11-14 00:51 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyBlockThreadHandler.java
> +
```suggestion
```

2023-11-14 00:51 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyBlockThreadHandler.java
> +
```suggestion
```

2023-11-14 00:51 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyBlockThreadHandler.java
> +            return;
```suggestion
            }
            
            return;
```

2023-11-14 00:51 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/util/watcher/rss/xmlparsers/SkyBlockThreadHandler.java
> +            return;
```suggestion
            }
            
            return;
```

2023-11-14 01:18 UTC, merged