QOL, Fixes and new Shortcuts
TheMGRF/NerdBot pull request #43
Opened 2023-01-22 22:50 UTC by RapidThrower264

- Adds new parameter (handle line breaks) which can be set to disable the automatic line break before the item's type
  - Ideally prevents the need to do "custom item type" handling when trying to put `*Soulbound*` or others at the end
- Moves Stat parsing away from `StringColorParser`
- Improved color code readability when there is an invalid character code
- Fixes special flags for the `REQUIRE` stat to being placed after the text
- Implements secondary color (could be implemented wrong)
- Added new Stats (shortcuts)
  - `REFORGEABLE` - `%%DARK_GRAY%%This item can be reforged!`
  - `ITEM_STAT_RED`, `ITEM_STAT_GREEN`, `ITEM_STAT_PURPLE`
     - Creates an item stat with the stat, color and amount. Requires 2 more parameters.
     - Usage: `%%ITEM_STAT_RED:<Stat>:<Amount>%%` turns into `%%GRAY%%<Stat>: %%RED%%<Amount>%%GRAY%%`

2023-01-26 00:21 UTC, Aerhhh commented
@RapidThrower24 it seems that stats don't have the colour applied to them, is it meant to be like this?
![image](https://user-images.githubusercontent.com/22944369/214724593-3ca7cfa4-bbc5-4e4b-aee8-1968dcb9388a.png)

2023-01-26 00:23 UTC, Aerhhh requested changes

2023-01-26 00:23 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/command/ItemGenCommand.java
> +            @Optional @AppOption(description = "If you will handle line breaks at the end of the item's description") String handleLineBreaks
Change this to a boolean

2023-01-26 00:23 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/command/ItemGenCommand.java
> +            if (handleLineBreaks == null || !handleLineBreaks.equalsIgnoreCase("true")) {
With the above change
```suggestion
            if (!handleLineBreaks) {
```

2023-01-26 03:35 UTC, RapidThrower264 commented
> @RapidThrower264 it seems that stats don't have the colour applied to them, is it meant to be like this?
> 
> The description is `%%PET_LUCK:1030%%` in the example

Some stats had secondary colors (`PET_LUCK`, `ATTACK_SPEED`, `HEALTH` and `SPEED`) included with then, but there was no implementation which used them.

2023-01-29 00:06 UTC, Aerhhh requested changes

2023-01-29 00:06 UTC, Aerhhh commented on src/main/java/net/hypixel/nerdbot/generator/StatColorParser.java
> +    /**
Being nitpicky but put a blank line here

2023-01-29 00:20 UTC, Aerhhh approved these changes

2023-01-29 00:20 UTC, merged