New Stats and `/itemgenparse`
TheMGRF/NerdBot pull request #72
Opened 2023-04-11 07:39 UTC by RapidThrower264

- Adds a new command `/itemgenparse` which will convert the display tag in the NBT of an item into a format which is displayable with the bot.
    - This should only accept a full JSON object with both a `Name` string and `Lore` array.
- Adds new stats `ABILITY` which acts similar to `ITEM_STAT_GREEN`
    - `%%ABILITY:Instant Transmission:RIGHT CLICK%%` -> `%%GOLD%%Ability: Instant Transmission%%YELLOW%%%%BOLD%%RIGHT CLICK`
-  Adds new stat `COOLDOWN` which puts the text after it in green
- Fix for the items description from being chopped off
- Fix for the `itemgen` command displaying a message in channels it isn't supposed to
- Fix for being able to set the line length to 0
- Fix typos in comments and added missing function comments

2023-04-11 13:19 UTC, mrkeith782 requested changes

2023-04-11 13:19 UTC, mrkeith782 commented on src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java
> +        JsonArray itemLoreArray;
why is the description being parsed as a JsonArray when it could be a string?

2023-04-11 13:19 UTC, mrkeith782 commented on src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java
> +    public void parseItemDescription(GuildSlashEvent event,
/infogen, located in `askForInfo()` should be updated explaining why this command exists

2023-04-11 23:14 UTC, RapidThrower264 commented on src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java
> +            itemJSON = NerdBotApp.GSON.fromJson(description, JsonObject.class);
The command was mainly aimed to allow users can quickly copy the formatting of an item and make changes to it for a suggestion.

2023-04-11 23:26 UTC, RapidThrower264 commented on src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java
> +            event.reply("The config for the item generating channel is not ready yet. Try again later!").setEphemeral(true).queue();
It seemed to work fine when testing as it replys immediately after running the command in the wrong channel

2023-04-12 05:43 UTC, mrkeith782 commented on src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java
> +            event.reply("The config for the item generating channel is not ready yet. Try again later!").setEphemeral(true).queue();
alright i trust you

2023-04-12 05:53 UTC, mrkeith782 commented on src/main/java/net/hypixel/nerdbot/command/ItemGenCommands.java
> +            itemJSON = NerdBotApp.GSON.fromJson(description, JsonObject.class);
Alright that's reasonable; I think that there is still room for those to be optionals but that'll be up to you here

2023-04-13 04:58 UTC, merged